// <auto-generated />
using System;
using FakeEventGenerator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeEventGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(FakeEventGeneratorDBContext))]
    [Migration("20230814182949_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.EnvironmentVariable", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("EnvironmentVariable");

                    b.HasData(
                        new
                        {
                            Type = "Degree",
                            Value = 20
                        },
                        new
                        {
                            Type = "Light",
                            Value = 10
                        },
                        new
                        {
                            Type = "Humidity",
                            Value = 20
                        },
                        new
                        {
                            Type = "Sound",
                            Value = 30
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Human", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("FeelToDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Human");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c2d0a3c-868a-4233-9e0c-d4737c4018cc"),
                            BodyStatus = "Stand",
                            CoordinateX = 10,
                            CoordinateY = 74,
                            FeelToDegree = "Medium",
                            MentalStatus = "Busy",
                            Name = "Human1"
                        },
                        new
                        {
                            Id = new Guid("c6ba5308-eb22-431e-8886-cd2b37ad7fc7"),
                            BodyStatus = "Stand",
                            CoordinateX = 75,
                            CoordinateY = 65,
                            FeelToDegree = "Medium",
                            MentalStatus = "Normal",
                            Name = "Human2"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMovable")
                        .HasColumnType("bit");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50e06a28-098a-40f0-9483-9841fe41f925"),
                            CoordinateX = 55,
                            CoordinateY = 0,
                            Description = "House Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("43a35dff-ba06-43e8-bd58-4816fb50ba1d"),
                            CoordinateX = 55,
                            CoordinateY = 30,
                            Description = "LivingRoom Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("361fb835-b978-4e15-8bf4-c6e3f04abf51"),
                            CoordinateX = 15,
                            CoordinateY = 30,
                            Description = "Kitchen Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("524eb5c5-689f-4b4f-9423-4931f0587e74"),
                            CoordinateX = 90,
                            CoordinateY = 30,
                            Description = "Bathroom Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("e30e350c-a035-42f0-8bfa-31924043a0b3"),
                            CoordinateX = 25,
                            CoordinateY = 50,
                            Description = "Bedroom1 Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("e2239a69-88cf-46d0-b41d-aa8350e08882"),
                            CoordinateX = 75,
                            CoordinateY = 50,
                            Description = "Bedroom2 Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("c98c422a-0361-4c9e-8586-ded65f83f01c"),
                            CoordinateX = 25,
                            CoordinateY = 80,
                            Description = "Balcony Door1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("597ee846-e091-4eb8-9808-bad5f5a41d38"),
                            CoordinateX = 75,
                            CoordinateY = 80,
                            Description = "Balcony Door1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("16189e20-a390-441d-9577-bb306619d303"),
                            CoordinateX = 0,
                            CoordinateY = 65,
                            Description = "Bedroom1 Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("fd55dba4-b7a9-4d5f-b049-67235ee3fb7d"),
                            CoordinateX = 100,
                            CoordinateY = 65,
                            Description = "Bedroom2 Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("37505a1f-06ba-4afa-9b66-766f9910dddc"),
                            CoordinateX = 50,
                            CoordinateY = 100,
                            Description = "Balcony Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("136c2951-870c-44e4-9cea-621665bcafe7"),
                            CoordinateX = 40,
                            CoordinateY = 65,
                            Description = "Bedroom1 Bed",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("94d61dc0-2e8d-40eb-8bcd-2569f75dc301"),
                            CoordinateX = 49,
                            CoordinateY = 55,
                            Description = "Bedroom1 AirConditioner",
                            IsMovable = false,
                            MetaData = "",
                            Name = "AirConditioner1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("1cb48a6a-60b2-4ac5-ba48-467d1fc4aa38"),
                            CoordinateX = 10,
                            CoordinateY = 79,
                            Description = "Bedroom1 Computer",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Computer",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("30a68b44-99ed-44df-90e5-71378466423c"),
                            CoordinateX = 10,
                            CoordinateY = 75,
                            Description = "Bedroom1 Chair",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair11",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("a4648e7c-5285-475b-820f-238d1ad41d08"),
                            CoordinateX = 25,
                            CoordinateY = 65,
                            Description = "Bedroom1 Lamp",
                            IsMovable = false,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("c76a6f26-f861-4b42-9c62-4462024fbfdc"),
                            CoordinateX = 60,
                            CoordinateY = 65,
                            Description = "Bedroom2 Bed",
                            IsMovable = false,
                            MetaData = "{\"Tempreture\":20,\"Speed\":10}",
                            Name = "Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("46733dcc-b144-443c-8cf6-7bf6b0c60cf4"),
                            CoordinateX = 51,
                            CoordinateY = 55,
                            Description = "Bedroom2 AirConditioner",
                            IsMovable = false,
                            MetaData = "{\"Tempreture\":20,\"Speed\":10}",
                            Name = "AirConditioner2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("f8455bc0-b929-4c0a-86ac-fe7e8eab92a3"),
                            CoordinateX = 90,
                            CoordinateY = 79,
                            Description = "Bedroom2 Laptop",
                            IsMovable = true,
                            MetaData = "{\"Charge\":90}",
                            Name = "Laptop",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("18c35fe8-3e6f-49e3-8b19-1e8bd4b104dd"),
                            CoordinateX = 90,
                            CoordinateY = 75,
                            Description = "Bedroom2 Chair",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair21",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("10b753a6-57ea-4372-83ef-d906b01c74a6"),
                            CoordinateX = 75,
                            CoordinateY = 65,
                            Description = "Bedroom2 Lamp",
                            IsMovable = false,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("ba7d9853-e268-4ec2-b0ce-c4289b3f5b3e"),
                            CoordinateX = 15,
                            CoordinateY = 1,
                            Description = "Kitchen Oven",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Oven",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("f47ed837-3454-433c-8f0f-e3108d2700ec"),
                            CoordinateX = 1,
                            CoordinateY = 15,
                            Description = "Kitchen Refrigerator",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Refrigerator",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("d19ce36b-e4ec-4b89-9020-1c1dd1f284b6"),
                            CoordinateX = 29,
                            CoordinateY = 15,
                            Description = "Kitchen WashingMachine",
                            IsMovable = false,
                            MetaData = "",
                            Name = "WashingMachine",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("3a6b7b33-ba8e-430b-8f54-c0160deccb2d"),
                            CoordinateX = 25,
                            CoordinateY = 1,
                            Description = "Kitchen DishWasher",
                            IsMovable = false,
                            MetaData = "",
                            Name = "DishWasher",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("8042f5b4-b929-4641-877f-eebf201e43bc"),
                            CoordinateX = 15,
                            CoordinateY = 15,
                            Description = "Kitchen Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("91e8e7a2-8caf-48b3-80f3-4198a4dc10b8"),
                            CoordinateX = 79,
                            CoordinateY = 15,
                            Description = "LivingRoom TV",
                            IsMovable = false,
                            MetaData = "{\"Channel\":1,\"Sound\":20}",
                            Name = "TV",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("d67e7534-1ffe-43ab-80a7-671fb5e744b1"),
                            CoordinateX = 70,
                            CoordinateY = 20,
                            Description = "LivingRoom Sofa1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Sofa1",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("bc811814-6dcf-4f3d-a334-ab744bff475e"),
                            CoordinateX = 70,
                            CoordinateY = 10,
                            Description = "LivingRoom Sofa2",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Sofa2",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("ba89e02a-c081-4d15-ab7a-8aa04261f7ce"),
                            CoordinateX = 60,
                            CoordinateY = 15,
                            Description = "LivingRoom Sofa3",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Sofa3",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("2164b445-7313-4028-bec3-ec5eef661df2"),
                            CoordinateX = 40,
                            CoordinateY = 15,
                            Description = "LivingRoom Table",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Table",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("c0f1e100-8ea0-48ec-876c-de9b0f734599"),
                            CoordinateX = 35,
                            CoordinateY = 15,
                            Description = "LivingRoom Chair1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair1",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("a90a860a-9683-46c9-8ab3-cd94b64c3355"),
                            CoordinateX = 45,
                            CoordinateY = 15,
                            Description = "LivingRoom Chair2",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair2",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("8348e3ee-c646-43f6-a98e-56ed2ad7167e"),
                            CoordinateX = 40,
                            CoordinateY = 10,
                            Description = "LivingRoom Chair3",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair3",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("813fb3b9-0d03-4f42-9854-690516eb8abc"),
                            CoordinateX = 40,
                            CoordinateY = 20,
                            Description = "LivingRoom Chair4",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair4",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("9802903f-666d-47a8-9077-8921ba275bcc"),
                            CoordinateX = 40,
                            CoordinateY = 29,
                            Description = "LivingRoom AirConditioner",
                            IsMovable = false,
                            MetaData = "{\"Tempreture\":20,\"Speed\":10}",
                            Name = "AirConditioner3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("dad4e662-0055-4f64-b138-c623b543d986"),
                            CoordinateX = 55,
                            CoordinateY = 15,
                            Description = "LivingRoom Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp4",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("2ea68b9a-608f-4905-bc9e-c12d4ca59be1"),
                            CoordinateX = 90,
                            CoordinateY = 15,
                            Description = "Bathroom Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp5",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("60103d9a-7924-4cf3-9d92-d288aab5f5c0"),
                            CoordinateX = 50,
                            CoordinateY = 90,
                            Description = "Balcony Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp6",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("91cf5265-9fc4-4f2c-8040-16bd4a66836c"),
                            CoordinateX = 50,
                            CoordinateY = 40,
                            Description = "Corridor Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp7",
                            State = "Off",
                            Type = "Electronic"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.PartOfHouse", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coordinate1X")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate1Y")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate2X")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate2Y")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("PartOfHouse");

                    b.HasData(
                        new
                        {
                            Type = "House",
                            Coordinate1X = 0,
                            Coordinate1Y = 0,
                            Coordinate2X = 100,
                            Coordinate2Y = 100
                        },
                        new
                        {
                            Type = "LivingRoom",
                            Coordinate1X = 0,
                            Coordinate1Y = 0,
                            Coordinate2X = 30,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Kitchen",
                            Coordinate1X = 30,
                            Coordinate1Y = 0,
                            Coordinate2X = 80,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Bathroom",
                            Coordinate1X = 80,
                            Coordinate1Y = 0,
                            Coordinate2X = 100,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Corridor",
                            Coordinate1X = 0,
                            Coordinate1Y = 30,
                            Coordinate2X = 100,
                            Coordinate2Y = 50
                        },
                        new
                        {
                            Type = "Bedroom1",
                            Coordinate1X = 0,
                            Coordinate1Y = 50,
                            Coordinate2X = 50,
                            Coordinate2Y = 80
                        },
                        new
                        {
                            Type = "Bedroom2",
                            Coordinate1X = 50,
                            Coordinate1Y = 50,
                            Coordinate2X = 100,
                            Coordinate2Y = 80
                        },
                        new
                        {
                            Type = "Balcony",
                            Coordinate1X = 0,
                            Coordinate1Y = 80,
                            Coordinate2X = 100,
                            Coordinate2Y = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
