// <auto-generated />
using System;
using FakeEventGenerator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeEventGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(FakeEventGeneratorDBContext))]
    [Migration("20230817115430_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartPossibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActionAggregate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            Delay = 500,
                            Description = "Open Door1 Of Balcony",
                            Name = "Open-BalconyDoor1",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            Delay = 500,
                            Description = "Move To Balcony Human1 Via Bedroom1",
                            Name = "Move-Balcony-Bedroom1",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            Delay = 100,
                            Description = "Open Window Of Balcony",
                            Name = "Open-BalconyWindow",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            Delay = 50,
                            Description = "Sit Under BalconyWindow",
                            Name = "Sit-BalconyWindow",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            Delay = 1500,
                            Description = "Open Door Of Bedroom2",
                            Name = "Open-Bedroom2Door",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            Delay = 500,
                            Description = "Move To Corridor Human2 Via Bedroom2",
                            Name = "Move-Corridor-Bedroom1",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            Delay = 400,
                            Description = "Open Window Of Balcony",
                            Name = "Open-LivinRoomDoor",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            Delay = 100,
                            Description = "Move To LivingRoom Human2 Via Corridor",
                            Name = "Move-LivingRoom-Corridor",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            Delay = 800,
                            Description = "Sit On Sofa1",
                            Name = "Sit-Sofa1",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            Delay = 200,
                            Description = "Turn On TV",
                            Name = "On-TV",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            Delay = 350,
                            Description = "Increase Sound Of TV",
                            Name = "Increase-Sound",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            Delay = 350,
                            Description = "Decrease Sound Of TV",
                            Name = "Decrease-Sound",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            Delay = 600,
                            Description = "Turn On AirConditioner3",
                            Name = "On-AirConditioner3",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            Delay = 200,
                            Description = "Decrease Degree Of AirConditioner3",
                            Name = "Decrease-Degree",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("fa1998cf-ebb5-40ac-bfb3-4e0c8b13673f"),
                            Delay = 200,
                            Description = "Human2 Stand In LivingRoom",
                            Name = "Stand-LivingRoom",
                            StartPossibility = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCaseExpectation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("ActionCondition");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1440e890-7fe7-42fe-beff-d845a68b9117"),
                            ActionAggregateId = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Bedroom1",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("d5994f8d-63dd-4d2e-b842-f05e1bb7bccf"),
                            ActionAggregateId = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("fa0c8736-61b0-4734-9794-92dbea142d75"),
                            ActionAggregateId = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            CaseStudy = "BalconyDoor1",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("3db5eac1-f373-4076-892e-a60fff3b1d33"),
                            ActionAggregateId = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Bedroom1",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("b8c88202-0bb6-404f-9482-db6bf556dba8"),
                            ActionAggregateId = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("f085eec9-1d9c-4dd3-9ee3-04ef3e156bc1"),
                            ActionAggregateId = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            CaseStudy = "BalconyDoor1",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("eb164d41-2d16-4ed4-9707-9b01d49ca051"),
                            ActionAggregateId = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Balcony",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("fa5602ea-5e4a-4731-b64e-7e44fdd0251d"),
                            ActionAggregateId = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("1cbf85a6-f853-4886-9460-09a0d7bafdaa"),
                            ActionAggregateId = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Balcony",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("7f8646a5-de3e-417e-9195-ebc11d274f14"),
                            ActionAggregateId = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIsNot",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("b551a8cd-d8d4-42ee-a667-0e278c95825b"),
                            ActionAggregateId = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Tired",
                            ConditionCaseType = "StateIs",
                            ConditionType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("d1f4e830-4c78-4016-9084-eab6e2aec4c5"),
                            ActionAggregateId = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            CaseStudy = "BalconyWindow",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("79f1b299-739f-4027-b35a-9745d8cf0ea0"),
                            ActionAggregateId = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Bedroom2",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("7ac1065c-cddc-4581-9359-10b12e007007"),
                            ActionAggregateId = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("b0122923-6e02-4ada-9835-7fb26647b445"),
                            ActionAggregateId = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            CaseStudy = "Bedroom1Door",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("bc512630-c87a-491f-a0b5-8a67dabcd90c"),
                            ActionAggregateId = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Bedroom2",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("4ddb0264-a946-477e-a84e-127d6e96c131"),
                            ActionAggregateId = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("bc1163fe-e4fa-43a4-bb05-7dfafb68dd29"),
                            ActionAggregateId = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            CaseStudy = "Bedroom2Door",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("1ea4f462-d31a-48a2-a3f3-811af48ebd6c"),
                            ActionAggregateId = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("5ec2ca1d-2ef9-4a21-a76d-9c7e19af1404"),
                            ActionAggregateId = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("40654310-8f3d-4667-9884-686f2e40b2fe"),
                            ActionAggregateId = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            CaseStudy = "LivingRoomDoor",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("17ab0825-c824-4487-8fef-11c951dd4eed"),
                            ActionAggregateId = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("5c3fdcef-8260-4f67-9a89-3b4961dda817"),
                            ActionAggregateId = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("e9e406f8-4553-47bc-8e29-f708f3ffcefa"),
                            ActionAggregateId = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            CaseStudy = "LivingRoomDoor",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("f9670e2d-f906-4282-a1d8-12e9c7b9dc28"),
                            ActionAggregateId = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("5797f54e-1985-4674-afd5-84e29e6fda93"),
                            ActionAggregateId = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("d3d6bfa4-aa1f-486d-a2f3-0521328ef56e"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("0ecb932d-d5a2-42f7-9e36-6510e6df4fa3"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("979d8822-23a2-4040-b961-60ea24a724f0"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            CaseStudy = "TV",
                            ConditionCaseExpectation = "Off",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("4958a793-fc1a-4a1f-8e38-c173fe7d4745"),
                            ActionAggregateId = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("0e56ed70-eba5-41b2-80d4-a251671a34fa"),
                            ActionAggregateId = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("5e7ff93b-20fc-4424-b4ec-e29de6b7333e"),
                            ActionAggregateId = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            CaseStudy = "TV",
                            ConditionCaseExpectation = "On",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("0c05eb49-25fa-4f19-9f17-2345067337f9"),
                            ActionAggregateId = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("53bf4d06-af87-4b8e-b7a2-969c381916e2"),
                            ActionAggregateId = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("67c2b180-6957-41c7-a126-68199208c698"),
                            ActionAggregateId = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            CaseStudy = "TV",
                            ConditionCaseExpectation = "On",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("0953a8c6-b619-4316-8d20-8ca6f50e2680"),
                            ActionAggregateId = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("77a28069-f538-4e3e-9c3c-495f8f4974c1"),
                            ActionAggregateId = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("ac212868-830f-47ab-9489-4ef739d3248d"),
                            ActionAggregateId = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("17d39fe6-6940-4e3e-a6f8-b40bb9ed1c37"),
                            ActionAggregateId = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("8f19437b-4af9-4083-8f38-76e7484dc2e2"),
                            ActionAggregateId = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            CaseStudy = "AirConditioner3",
                            ConditionCaseExpectation = "On",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("05db8ee0-e98c-4442-afb4-0026cee2f9d9"),
                            ActionAggregateId = new Guid("fa1998cf-ebb5-40ac-bfb3-4e0c8b13673f"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("ff08e005-e6a1-4193-ad4f-a296703e2b29"),
                            ActionAggregateId = new Guid("fa1998cf-ebb5-40ac-bfb3-4e0c8b13673f"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIsNot",
                            ConditionType = "HumanBodyStatus"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCaseChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("ActionResult");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1931ac5-fdd8-42ba-ae41-872c40f60319"),
                            ActionAggregateId = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "25-79",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("a99029a0-a3ff-4644-aeca-31ae1cf96428"),
                            ActionAggregateId = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            CaseStudy = "BalconyDoor1",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("6b60b803-a85f-463b-b2d4-cc9654e10afc"),
                            ActionAggregateId = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "25-81",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("2fbceaba-bfb4-4bd3-98ef-5ea9cfc4b607"),
                            ActionAggregateId = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "50-99",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("4da22339-a4b0-4a00-a09a-005b536f27e8"),
                            ActionAggregateId = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            CaseStudy = "BalconyWindow",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("c6fe9a8a-26ac-48a7-94b5-9ceb6f292af8"),
                            ActionAggregateId = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            CaseStudy = "Light",
                            ResultCaseChange = "20-IF:Day",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("fbc39e98-19ac-42c6-9c72-944dc4555c29"),
                            ActionAggregateId = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Sit",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("0a2d855f-ca55-480d-9cd6-a8e461a1e050"),
                            ActionAggregateId = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Normal",
                            ResultCaseType = "State",
                            ResultType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("867ef767-db92-4436-a8e6-412f5098fa98"),
                            ActionAggregateId = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "75-51",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("d579704e-bb80-48b7-9ed3-9daf5e7ea6bc"),
                            ActionAggregateId = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            CaseStudy = "Bedroom2Door",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("24806382-d8c2-4322-bfb8-a21e8eca5cc7"),
                            ActionAggregateId = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "75-49",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("23169975-0476-4e07-b186-b22e326dd9cb"),
                            ActionAggregateId = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "55-31",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("9d1c631f-6fbe-4237-8aed-de7c1d4f58e5"),
                            ActionAggregateId = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            CaseStudy = "LivingRoomDoor",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("909f66e7-274d-42a5-b145-94c32d2e3113"),
                            ActionAggregateId = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "55-29",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("30c7ebfa-3c36-4d7c-a695-97d4e76e0608"),
                            ActionAggregateId = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "70-20",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("a7a2244d-9e16-4589-bee9-aac411e4a266"),
                            ActionAggregateId = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            CaseStudy = "Sofa1",
                            ResultCaseChange = "Full",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("1f9338bd-7c53-42eb-9223-339cef151d56"),
                            ActionAggregateId = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Sit",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("e27c180e-9ded-49e6-9b2a-ef08eb50dab9"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Normal",
                            ResultCaseType = "State",
                            ResultType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("7a6fb182-d596-4e98-b82a-3b147493a6f9"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            CaseStudy = "TV",
                            ResultCaseChange = "On",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("15ce581c-b394-4d67-8ba3-62a9db771bb4"),
                            ActionAggregateId = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            CaseStudy = "Light",
                            ResultCaseChange = "10",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("bad013d2-e3a5-4d0a-bf33-5cc640243774"),
                            ActionAggregateId = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            CaseStudy = "Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("e5b5d2cb-7c7b-4c20-b7e8-f203fef4fbd1"),
                            ActionAggregateId = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            CaseStudy = "TV-Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Increase",
                            ResultType = "ItemMetaData"
                        },
                        new
                        {
                            Id = new Guid("faca3b9c-2a6f-47a9-b6b9-0f6ac32697f0"),
                            ActionAggregateId = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            CaseStudy = "Light",
                            ResultCaseChange = "10",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("4479990a-9fb2-4a42-af09-36d2f4d686a0"),
                            ActionAggregateId = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            CaseStudy = "Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Decrease",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("483378b3-f3a6-4cb4-a665-09088b3f7713"),
                            ActionAggregateId = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            CaseStudy = "TV-Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Decrease",
                            ResultType = "ItemMetaData"
                        },
                        new
                        {
                            Id = new Guid("a2ba5d39-beba-46e4-9402-e82d897f0aa4"),
                            ActionAggregateId = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "40-28",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("2f3225bd-e018-48e4-806e-871aaab0fc27"),
                            ActionAggregateId = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            CaseStudy = "AirConditioner3",
                            ResultCaseChange = "On",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("fb8bb6e1-f627-4e9b-be83-da3c86ba7339"),
                            ActionAggregateId = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Cold",
                            ResultCaseType = "State",
                            ResultType = "HumanFeelToDegree"
                        },
                        new
                        {
                            Id = new Guid("cfa118b1-1c44-475c-9bea-f5d31a0d6004"),
                            ActionAggregateId = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            CaseStudy = "AirConditioner3-Temperature",
                            ResultCaseChange = "5-15",
                            ResultCaseType = "Decrease",
                            ResultType = "ItemMetaData"
                        },
                        new
                        {
                            Id = new Guid("9344652a-2d26-4150-afd2-49cbeca93443"),
                            ActionAggregateId = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            CaseStudy = "Degree",
                            ResultCaseChange = "7",
                            ResultCaseType = "Decrease",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("a7d65d82-25c8-4da9-aecc-90cf17752ee4"),
                            ActionAggregateId = new Guid("fa1998cf-ebb5-40ac-bfb3-4e0c8b13673f"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Stand",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.EnvironmentVariable", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("EnvironmentVariable");

                    b.HasData(
                        new
                        {
                            Type = "Degree",
                            Value = 20
                        },
                        new
                        {
                            Type = "Light",
                            Value = 10
                        },
                        new
                        {
                            Type = "Humidity",
                            Value = 20
                        },
                        new
                        {
                            Type = "Sound",
                            Value = 30
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Human", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("FeelToDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Human");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36450e4c-75eb-4ea2-a843-a90010fff179"),
                            BodyStatus = "Stand",
                            CoordinateX = 10,
                            CoordinateY = 74,
                            FeelToDegree = "Medium",
                            MentalStatus = "Tired",
                            Name = "Human1"
                        },
                        new
                        {
                            Id = new Guid("001203e2-9508-4c1d-b797-a746eb45e874"),
                            BodyStatus = "Stand",
                            CoordinateX = 75,
                            CoordinateY = 65,
                            FeelToDegree = "Medium",
                            MentalStatus = "Bored",
                            Name = "Human2"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMovable")
                        .HasColumnType("bit");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1443d18-c717-4349-80cf-dbdc419940a9"),
                            CoordinateX = 55,
                            CoordinateY = 0,
                            Description = "House Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "HouseDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("5ce97b28-63bc-49e1-b42f-007f33e6ebda"),
                            CoordinateX = 55,
                            CoordinateY = 30,
                            Description = "LivingRoom Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "LivingRoomDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("09473cf1-c034-48b2-a4dd-047ac3db8988"),
                            CoordinateX = 15,
                            CoordinateY = 30,
                            Description = "Kitchen Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "KitchenDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("6d42b09f-db38-4224-9c7e-4f394b173174"),
                            CoordinateX = 90,
                            CoordinateY = 30,
                            Description = "Bathroom Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BathroomDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("9213b068-e328-4a6c-8379-61a061e232c4"),
                            CoordinateX = 25,
                            CoordinateY = 50,
                            Description = "Bedroom1 Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom1Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("63e11197-b517-42f0-b874-3b76bae68f21"),
                            CoordinateX = 75,
                            CoordinateY = 50,
                            Description = "Bedroom2 Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom2Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("ee716306-5f22-49ce-9d75-314071265472"),
                            CoordinateX = 25,
                            CoordinateY = 80,
                            Description = "Balcony Door1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BalconyDoor1",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("2738e12b-5315-4433-b6ad-bcb90e615499"),
                            CoordinateX = 75,
                            CoordinateY = 80,
                            Description = "Balcony Door2",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BalconyDoor2",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("9c048d63-42fa-4f62-8367-ded8a8fe4d45"),
                            CoordinateX = 0,
                            CoordinateY = 65,
                            Description = "Bedroom1 Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom1Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("b9fe06c9-6ba8-408d-9d39-86f64667b13d"),
                            CoordinateX = 100,
                            CoordinateY = 65,
                            Description = "Bedroom2 Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom2Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("e4584cf0-a363-488c-b141-cd2409e26573"),
                            CoordinateX = 50,
                            CoordinateY = 100,
                            Description = "Balcony Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BalconyWindow",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("6a6642e5-ca97-49d6-a45f-0008c1766613"),
                            CoordinateX = 40,
                            CoordinateY = 65,
                            Description = "Bedroom1 Bed",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom1Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("66bd4e1d-af17-4bbb-94c2-188bac67ea36"),
                            CoordinateX = 49,
                            CoordinateY = 55,
                            Description = "Bedroom1 AirConditioner",
                            IsMovable = false,
                            MetaData = "",
                            Name = "AirConditioner1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("32df68d2-e0ce-4e3c-aa51-b4451f5cc93a"),
                            CoordinateX = 10,
                            CoordinateY = 79,
                            Description = "Bedroom1 Computer",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Computer",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("e2de4be0-cc7a-49db-a354-7720ad736613"),
                            CoordinateX = 10,
                            CoordinateY = 75,
                            Description = "Bedroom1 Chair",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair11",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("92018d54-7aa2-4a14-9bc7-fa62ddb2e886"),
                            CoordinateX = 25,
                            CoordinateY = 65,
                            Description = "Bedroom1 Lamp",
                            IsMovable = false,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("85357074-d5ed-4ca0-a4c7-499f9ca3f276"),
                            CoordinateX = 60,
                            CoordinateY = 65,
                            Description = "Bedroom2 Bed",
                            IsMovable = false,
                            MetaData = "{\"Temperature\":20,\"Speed\":10}",
                            Name = "Bedroom2Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("42bd8dcc-b46a-4460-bea6-a287e6903b0b"),
                            CoordinateX = 51,
                            CoordinateY = 55,
                            Description = "Bedroom2 AirConditioner",
                            IsMovable = false,
                            MetaData = "{\"Temperature\":20,\"Speed\":10}",
                            Name = "AirConditioner2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("81bd2d0b-59c0-40c0-9872-a0613e00ece4"),
                            CoordinateX = 90,
                            CoordinateY = 79,
                            Description = "Bedroom2 Laptop",
                            IsMovable = true,
                            MetaData = "{\"Charge\":90,\"IsInCharge\":false}",
                            Name = "Laptop",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("def515b1-59c9-4971-8aa2-b0a68bc3c8c3"),
                            CoordinateX = 90,
                            CoordinateY = 75,
                            Description = "Bedroom2 Chair",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair21",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("fb5b7c72-7408-4b07-ad91-eb115cf1f602"),
                            CoordinateX = 75,
                            CoordinateY = 65,
                            Description = "Bedroom2 Lamp",
                            IsMovable = false,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("9d085476-c8af-44e1-a152-c6fd230856f6"),
                            CoordinateX = 15,
                            CoordinateY = 1,
                            Description = "Kitchen Oven",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Oven",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("7b170b4d-ec88-42b2-b3d5-81537626403b"),
                            CoordinateX = 1,
                            CoordinateY = 15,
                            Description = "Kitchen Refrigerator",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Refrigerator",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("719d4b42-5f23-450e-b59f-0eefee12e46f"),
                            CoordinateX = 29,
                            CoordinateY = 15,
                            Description = "Kitchen WashingMachine",
                            IsMovable = false,
                            MetaData = "",
                            Name = "WashingMachine",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("272cc02d-ec3c-400b-99b2-873afea2ea32"),
                            CoordinateX = 25,
                            CoordinateY = 1,
                            Description = "Kitchen DishWasher",
                            IsMovable = false,
                            MetaData = "",
                            Name = "DishWasher",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("94bdaddb-5c69-45b3-a665-675c2d5b419c"),
                            CoordinateX = 15,
                            CoordinateY = 15,
                            Description = "Kitchen Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("c34371e5-33f5-4978-85c7-3faadd54da9a"),
                            CoordinateX = 79,
                            CoordinateY = 15,
                            Description = "LivingRoom TV",
                            IsMovable = false,
                            MetaData = "{\"Channel\":1,\"Sound\":60}",
                            Name = "TV",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("4932ebcc-e186-4341-a8b7-ad62d8be0d0e"),
                            CoordinateX = 70,
                            CoordinateY = 20,
                            Description = "LivingRoom Sofa1",
                            IsMovable = false,
                            MetaData = "{\"Capacity\":1}",
                            Name = "Sofa1",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("ef1d4bbb-c278-4ada-a1de-42e4f13c455e"),
                            CoordinateX = 70,
                            CoordinateY = 10,
                            Description = "LivingRoom Sofa2",
                            IsMovable = false,
                            MetaData = "{\"Capacity\":2}",
                            Name = "Sofa2",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("470979e6-7985-4edc-a7a0-27edf36bfeff"),
                            CoordinateX = 60,
                            CoordinateY = 15,
                            Description = "LivingRoom Sofa3",
                            IsMovable = false,
                            MetaData = "{\"Capacity\":3}",
                            Name = "Sofa3",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("ba6d2e1b-1967-44a0-af35-bfc85164534e"),
                            CoordinateX = 40,
                            CoordinateY = 15,
                            Description = "LivingRoom Table",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Table",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("3cdc3e89-ee65-49ee-a76d-1b47652a55fc"),
                            CoordinateX = 35,
                            CoordinateY = 15,
                            Description = "LivingRoom Chair1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair1",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("c8ca1f1a-1e31-414d-96de-3e4b1c91bdb3"),
                            CoordinateX = 45,
                            CoordinateY = 15,
                            Description = "LivingRoom Chair2",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair2",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("943d0793-5ead-4f0e-a6db-991a7642b6f0"),
                            CoordinateX = 40,
                            CoordinateY = 10,
                            Description = "LivingRoom Chair3",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair3",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("8c325e0c-ed21-4398-b78a-70ebd9738394"),
                            CoordinateX = 40,
                            CoordinateY = 20,
                            Description = "LivingRoom Chair4",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair4",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("9500f608-eba5-49b6-b449-41af6199f4d9"),
                            CoordinateX = 40,
                            CoordinateY = 29,
                            Description = "LivingRoom AirConditioner",
                            IsMovable = false,
                            MetaData = "{\"Temperature\":20,\"Speed\":10}",
                            Name = "AirConditioner3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("4529e8e1-fe49-4ba6-a3f2-d851faa37860"),
                            CoordinateX = 55,
                            CoordinateY = 15,
                            Description = "LivingRoom Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp4",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("15dd878c-da00-49c2-b056-bf793b384954"),
                            CoordinateX = 90,
                            CoordinateY = 15,
                            Description = "Bathroom Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp5",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("a2c50e60-0ca8-49ff-b833-ef00ce0f5311"),
                            CoordinateX = 50,
                            CoordinateY = 90,
                            Description = "Balcony Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp6",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("04f26c34-5a1f-4f07-bab2-81fb88289450"),
                            CoordinateX = 50,
                            CoordinateY = 40,
                            Description = "Corridor Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp7",
                            State = "Off",
                            Type = "Electronic"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.NextAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<int>("Possibility")
                        .HasColumnType("int");

                    b.HasKey("Id", "ActionAggregateId");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("NextAction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            ActionAggregateId = new Guid("036815aa-a179-4039-b2a4-72c13dcda1be"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            ActionAggregateId = new Guid("69c6f8c5-de4b-4bd2-b682-b60ab996cc7c"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("21108caa-542c-4dac-b4cf-1f56af9d422f"),
                            ActionAggregateId = new Guid("e9b5be47-94e9-4a0e-a50b-85e0ce45890e"),
                            Delay = 100,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            ActionAggregateId = new Guid("5d7667fc-95a6-459a-9a87-5b91d0351f16"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            ActionAggregateId = new Guid("68b9a437-3062-4102-9bb7-11b868b2bcde"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            ActionAggregateId = new Guid("b44848cd-8621-4899-b100-ada573c3d269"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            ActionAggregateId = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            ActionAggregateId = new Guid("fbca3458-5fbd-4efc-9132-36a899d00eda"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("8a27ee4c-bdce-4b56-9e35-375b70597271"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("d952318f-bbcf-45f5-8682-00a550804568"),
                            ActionAggregateId = new Guid("a119641f-72b9-4e0c-8a57-543ffdb161db"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            ActionAggregateId = new Guid("4591c499-74d5-426b-ad52-bd9052344511"),
                            Delay = 350,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("4fa6065c-1c81-454d-baab-a1417bfca94e"),
                            ActionAggregateId = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("535537de-922c-46ca-a8b7-7f32225253c6"),
                            ActionAggregateId = new Guid("fa1998cf-ebb5-40ac-bfb3-4e0c8b13673f"),
                            Delay = 200,
                            Possibility = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.PartOfHouse", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coordinate1X")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate1Y")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate2X")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate2Y")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("PartOfHouse");

                    b.HasData(
                        new
                        {
                            Type = "House",
                            Coordinate1X = 0,
                            Coordinate1Y = 0,
                            Coordinate2X = 100,
                            Coordinate2Y = 100
                        },
                        new
                        {
                            Type = "Kitchen",
                            Coordinate1X = 0,
                            Coordinate1Y = 0,
                            Coordinate2X = 30,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "LivingRoom",
                            Coordinate1X = 30,
                            Coordinate1Y = 0,
                            Coordinate2X = 80,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Bathroom",
                            Coordinate1X = 80,
                            Coordinate1Y = 0,
                            Coordinate2X = 100,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Corridor",
                            Coordinate1X = 0,
                            Coordinate1Y = 30,
                            Coordinate2X = 100,
                            Coordinate2Y = 50
                        },
                        new
                        {
                            Type = "Bedroom1",
                            Coordinate1X = 0,
                            Coordinate1Y = 50,
                            Coordinate2X = 50,
                            Coordinate2Y = 80
                        },
                        new
                        {
                            Type = "Bedroom2",
                            Coordinate1X = 50,
                            Coordinate1Y = 50,
                            Coordinate2X = 100,
                            Coordinate2Y = 80
                        },
                        new
                        {
                            Type = "Balcony",
                            Coordinate1X = 0,
                            Coordinate1Y = 80,
                            Coordinate2X = 100,
                            Coordinate2Y = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionCondition", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("Conditions")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionResult", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("Results")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.NextAction", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("NextActions")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionAggregate", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("NextActions");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
