// <auto-generated />
using System;
using FakeEventGenerator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeEventGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(FakeEventGeneratorDBContext))]
    [Migration("20240726180506_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndPossibility")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActionAggregate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23105c78-b2e5-4d0a-8c36-25941b402dac"),
                            Delay = 1500,
                            Description = "Open SafeBox",
                            EndPossibility = 0,
                            Name = "Open-SafeBox"
                        },
                        new
                        {
                            Id = new Guid("890c48e6-5ef6-494e-a2c4-553669331ca3"),
                            Delay = 1000,
                            Description = "Close SafeBox",
                            EndPossibility = 0,
                            Name = "Close-SafeBox"
                        },
                        new
                        {
                            Id = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            Delay = 500,
                            Description = "Open Door1 Of Balcony",
                            EndPossibility = 100,
                            Name = "Open-BalconyDoor1"
                        },
                        new
                        {
                            Id = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            Delay = 500,
                            Description = "Move To Balcony Human1 Via Bedroom1",
                            EndPossibility = 100,
                            Name = "Move-Balcony-Bedroom1"
                        },
                        new
                        {
                            Id = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            Delay = 100,
                            Description = "Open Window Of Balcony",
                            EndPossibility = 100,
                            Name = "Open-BalconyWindow"
                        },
                        new
                        {
                            Id = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            Delay = 50,
                            Description = "Sit Under BalconyWindow",
                            EndPossibility = 100,
                            Name = "Sit-BalconyWindow"
                        },
                        new
                        {
                            Id = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            Delay = 1500,
                            Description = "Open Door Of Bedroom2",
                            EndPossibility = 100,
                            Name = "Open-Bedroom2Door"
                        },
                        new
                        {
                            Id = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            Delay = 500,
                            Description = "Move To Corridor Human2 Via Bedroom2",
                            EndPossibility = 100,
                            Name = "Move-Corridor-Bedroom1"
                        },
                        new
                        {
                            Id = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            Delay = 400,
                            Description = "Open Door Of LivingRoom",
                            EndPossibility = 100,
                            Name = "Open-LivinRoomDoor"
                        },
                        new
                        {
                            Id = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            Delay = 100,
                            Description = "Move To LivingRoom Human2 Via Corridor",
                            EndPossibility = 100,
                            Name = "Move-LivingRoom-Corridor"
                        },
                        new
                        {
                            Id = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            Delay = 800,
                            Description = "Sit On Sofa1",
                            EndPossibility = 100,
                            Name = "Sit-Sofa1"
                        },
                        new
                        {
                            Id = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            Delay = 200,
                            Description = "Turn On TV",
                            EndPossibility = 50,
                            Name = "On-TV"
                        },
                        new
                        {
                            Id = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            Delay = 350,
                            Description = "Increase Sound Of TV",
                            EndPossibility = 100,
                            Name = "Increase-Sound"
                        },
                        new
                        {
                            Id = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            Delay = 350,
                            Description = "Decrease Sound Of TV",
                            EndPossibility = 100,
                            Name = "Decrease-Sound"
                        },
                        new
                        {
                            Id = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            Delay = 600,
                            Description = "Turn On AirConditioner3",
                            EndPossibility = 100,
                            Name = "On-AirConditioner3"
                        },
                        new
                        {
                            Id = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            Delay = 200,
                            Description = "Decrease Degree Of AirConditioner3",
                            EndPossibility = 100,
                            Name = "Decrease-Degree"
                        },
                        new
                        {
                            Id = new Guid("db116b9c-e998-498f-9ca3-f4e8eeeb4b8b"),
                            Delay = 200,
                            Description = "Human2 Stand In LivingRoom",
                            EndPossibility = 100,
                            Name = "Stand-LivingRoom"
                        },
                        new
                        {
                            Id = new Guid("509c51f0-8991-42e7-bd9f-8c26070d89b6"),
                            Delay = 2400,
                            Description = "Move to corridor via livingroom",
                            EndPossibility = 50,
                            Name = "Move-Corridor-LivingRoom"
                        },
                        new
                        {
                            Id = new Guid("b62ca4c5-73ca-462f-a89d-46e42f4fa4b9"),
                            Delay = 1100,
                            Description = "Open door of the kitchen",
                            EndPossibility = 100,
                            Name = "Open-Kitchen-Door"
                        },
                        new
                        {
                            Id = new Guid("8374b387-564a-46f1-8fe2-0d2da584eb4e"),
                            Delay = 500,
                            Description = "Move to kitchen form corridor",
                            EndPossibility = 100,
                            Name = "Move-Kitchen-Corridor"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCaseExpectation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("ActionCondition");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5afb842-d40e-4559-973f-06b99b19908a"),
                            ActionAggregateId = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Bedroom1",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("ddff0144-ec0f-49c2-89c4-16e53f72fcaa"),
                            ActionAggregateId = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("d7c28e01-1e28-4428-b975-a473911e09ae"),
                            ActionAggregateId = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            CaseStudy = "BalconyDoor1",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("a812f3c4-a49a-4240-b871-007bcf591352"),
                            ActionAggregateId = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Bedroom1",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("c6da2934-6898-4201-8f10-294dd4e48338"),
                            ActionAggregateId = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("04aa0cbc-a528-4df5-9a2b-fa7d48fb156e"),
                            ActionAggregateId = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            CaseStudy = "BalconyDoor1",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("b8ff6707-705c-475d-a507-4644f138e143"),
                            ActionAggregateId = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Balcony",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("4d77814a-077c-412d-83ab-b90fcbcfc180"),
                            ActionAggregateId = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("2dbbc7f0-8dda-4cb9-b420-395713292377"),
                            ActionAggregateId = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Balcony",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("35160ffe-e5e3-4180-ba24-ad397949c1fe"),
                            ActionAggregateId = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIsNot",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("1673317e-54b3-41c2-b4eb-16fe9bbcdcf4"),
                            ActionAggregateId = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Tired",
                            ConditionCaseType = "StateIs",
                            ConditionType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("3aa212e8-0136-4bd1-9230-513678860098"),
                            ActionAggregateId = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            CaseStudy = "BalconyWindow",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("0b338e8b-075e-4453-98f2-ce3bc0f3c857"),
                            ActionAggregateId = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Bedroom2",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("f7f0598d-42f7-45a4-aca2-f301c657364b"),
                            ActionAggregateId = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("6b51cbe5-6ced-405e-9619-3a80d2a5f446"),
                            ActionAggregateId = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            CaseStudy = "Bedroom1Door",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("83e192d0-624c-4fbf-bbe7-c588fddcdfc0"),
                            ActionAggregateId = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Bedroom2",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("7ef8a35a-3e34-4568-9e65-f68d24684ddb"),
                            ActionAggregateId = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("ea6c82f3-7bb9-4397-8173-982a4129b8a5"),
                            ActionAggregateId = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            CaseStudy = "Bedroom2Door",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("ccb228a8-905f-4139-9011-6effc4e3a87f"),
                            ActionAggregateId = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("6dc69896-07d4-42d0-b524-aa65795a6f2f"),
                            ActionAggregateId = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("72cad0d3-64f8-4f7a-87c1-56412182bcd5"),
                            ActionAggregateId = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            CaseStudy = "LivingRoomDoor",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("918e721d-9136-4889-be6a-75c0e962fc74"),
                            ActionAggregateId = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("e3b591e1-33a0-4ef5-806e-2d55b78712dd"),
                            ActionAggregateId = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("1a16ecf6-960f-4243-9084-dbe8d0f50166"),
                            ActionAggregateId = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            CaseStudy = "LivingRoomDoor",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("3d13d3ce-d59d-46f4-a307-b24afd9278d9"),
                            ActionAggregateId = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("84998220-35e8-4ce7-9b72-d5530bc9638f"),
                            ActionAggregateId = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("1a2a793b-82ad-48f8-bc1d-72d629de6ea8"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("e07b4b4f-521a-4ca6-ad72-ffcf96743177"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("a048ed34-99f9-40de-bf20-a3c8bea58fbb"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            CaseStudy = "TV",
                            ConditionCaseExpectation = "Off",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("e12e91c4-83e4-4ed3-beff-200d98696051"),
                            ActionAggregateId = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("fb335ea8-f8fe-4240-9aba-cd7b68133677"),
                            ActionAggregateId = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("9e23e601-128e-4933-8201-963f45da65b4"),
                            ActionAggregateId = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            CaseStudy = "TV",
                            ConditionCaseExpectation = "On",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("5bb44c74-9ec4-4502-9ae0-57b06bac4c7d"),
                            ActionAggregateId = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("5ebe1d82-5c09-4f99-bd37-2e8bcf76cfad"),
                            ActionAggregateId = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("50c14b0d-56cf-41e5-91dd-5e04c67b084e"),
                            ActionAggregateId = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            CaseStudy = "TV",
                            ConditionCaseExpectation = "On",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("79554513-d70a-4930-a0cc-b3c4e1cf08dd"),
                            ActionAggregateId = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("5be59fa4-fed7-40a8-8b18-359d56696e3b"),
                            ActionAggregateId = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("176f7753-e46d-4aa2-a668-e3019c5b37f2"),
                            ActionAggregateId = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("72c228f9-25e1-4576-9d69-610eab6b669f"),
                            ActionAggregateId = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("a40849c6-0205-48ce-9ff2-6bc3df51185a"),
                            ActionAggregateId = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            CaseStudy = "AirConditioner3",
                            ConditionCaseExpectation = "On",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("9b3333d2-15ec-407d-9487-160bbe4d3d62"),
                            ActionAggregateId = new Guid("db116b9c-e998-498f-9ca3-f4e8eeeb4b8b"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("daf0d027-7451-458e-b4a5-4ea51bad01ad"),
                            ActionAggregateId = new Guid("db116b9c-e998-498f-9ca3-f4e8eeeb4b8b"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIsNot",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("ae0c53a8-3bce-4c2d-a3b2-268fbe7dde01"),
                            ActionAggregateId = new Guid("509c51f0-8991-42e7-bd9f-8c26070d89b6"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "LivingRoom",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("a34fdac7-8f12-4285-98b5-ddff19462556"),
                            ActionAggregateId = new Guid("b62ca4c5-73ca-462f-a89d-46e42f4fa4b9"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("7af5037f-360c-4777-947f-7dee5e4d29cd"),
                            ActionAggregateId = new Guid("8374b387-564a-46f1-8fe2-0d2da584eb4e"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("d9d6fb3a-fa95-4367-a73c-f1bac6ba7bb2"),
                            ActionAggregateId = new Guid("8374b387-564a-46f1-8fe2-0d2da584eb4e"),
                            CaseStudy = "KitchenDoor",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("5e1e6949-68d9-4266-bd0d-510215750356"),
                            ActionAggregateId = new Guid("23105c78-b2e5-4d0a-8c36-25941b402dac"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("ff6119f2-4270-4b66-babf-60185904a187"),
                            ActionAggregateId = new Guid("890c48e6-5ef6-494e-a2c4-553669331ca3"),
                            CaseStudy = "Human2",
                            ConditionCaseExpectation = "Corridor",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("f708db86-11b9-4719-a034-dfcc3155255f"),
                            ActionAggregateId = new Guid("890c48e6-5ef6-494e-a2c4-553669331ca3"),
                            CaseStudy = "SafeBox",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCaseChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("ActionResult");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47784418-2658-4ea1-82f1-c51438d68f1e"),
                            ActionAggregateId = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Bedroom1",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("df69005a-e29f-40e2-bbf6-5ae756608a5c"),
                            ActionAggregateId = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            CaseStudy = "BalconyDoor1",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("720374ab-826f-4d80-aaf1-27779c57631b"),
                            ActionAggregateId = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Balcony",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("2221a339-f58f-49eb-ad14-84d50d64e1e1"),
                            ActionAggregateId = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Balcony",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("673c44ce-8e5e-40d6-986e-6c96b4389042"),
                            ActionAggregateId = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            CaseStudy = "BalconyWindow",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("4892b86a-225b-4161-aa1c-48e00776fb4d"),
                            ActionAggregateId = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            CaseStudy = "Light",
                            ResultCaseChange = "20-IF:Day",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("357780ee-2afe-487b-8516-e9dadfe23104"),
                            ActionAggregateId = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Sit",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("af1a0847-5936-456b-ad85-324742fa433e"),
                            ActionAggregateId = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Normal",
                            ResultCaseType = "State",
                            ResultType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("23e3ed81-55fa-4555-8101-e5a792fcafb8"),
                            ActionAggregateId = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Bedroom2",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("746402cd-9dca-43ef-ae5a-ae07387796b5"),
                            ActionAggregateId = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            CaseStudy = "Bedroom2Door",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("911f0585-a81a-4071-9725-6d1baec10937"),
                            ActionAggregateId = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Corridor",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("80e16184-bbaf-4323-bdef-17ac8823e646"),
                            ActionAggregateId = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Corridor",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("c51e6a74-c022-458a-829b-4702c429e0be"),
                            ActionAggregateId = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            CaseStudy = "LivingRoomDoor",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("a049277a-811d-44e8-8824-16779a2da720"),
                            ActionAggregateId = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "LivingRoom",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("8bcf30c7-3aea-440b-9b8e-121d437192cd"),
                            ActionAggregateId = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "LivingRoom",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("c70e9d2c-deb4-47d3-a858-726c63dc48a0"),
                            ActionAggregateId = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            CaseStudy = "Sofa1",
                            ResultCaseChange = "Full",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("839c68ce-a0aa-42da-9ecd-c344555d2445"),
                            ActionAggregateId = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Sit",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("1d40b181-8fbf-4d12-b3e9-91bcbd0d061a"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Normal",
                            ResultCaseType = "State",
                            ResultType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("dd191aa2-f877-4852-b593-cc6efd0e33b1"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            CaseStudy = "TV",
                            ResultCaseChange = "On",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("9f175cb2-590b-424f-80fa-202112c9e7b1"),
                            ActionAggregateId = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            CaseStudy = "Light",
                            ResultCaseChange = "10",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("be15eefa-3c05-45f7-a568-e90306a94060"),
                            ActionAggregateId = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            CaseStudy = "Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("752deb28-cb70-4f66-9982-87c1f1ea49b8"),
                            ActionAggregateId = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            CaseStudy = "TV-Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Increase",
                            ResultType = "ItemMetaData"
                        },
                        new
                        {
                            Id = new Guid("6a0a3fd6-88bc-4f9a-b3b8-207f556a4f24"),
                            ActionAggregateId = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            CaseStudy = "Light",
                            ResultCaseChange = "10",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("381f5caa-a8ff-4d1a-8939-f804d84ab940"),
                            ActionAggregateId = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            CaseStudy = "Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Decrease",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("b79ef17b-acd3-4c7b-9f5b-8620d9b9689b"),
                            ActionAggregateId = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            CaseStudy = "TV-Sound",
                            ResultCaseChange = "10-40",
                            ResultCaseType = "Decrease",
                            ResultType = "ItemMetaData"
                        },
                        new
                        {
                            Id = new Guid("8af08c33-db4b-447b-a2d7-4636a45b2e92"),
                            ActionAggregateId = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "LivingRoom",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("5559a659-23b7-437b-99fb-931b259c651a"),
                            ActionAggregateId = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            CaseStudy = "AirConditioner3",
                            ResultCaseChange = "On",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("30a1930b-c815-4847-b370-f71c412d802d"),
                            ActionAggregateId = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Cold",
                            ResultCaseType = "State",
                            ResultType = "HumanFeelToDegree"
                        },
                        new
                        {
                            Id = new Guid("ebaa547b-5016-4c67-8ad5-6c9f2e389ef8"),
                            ActionAggregateId = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            CaseStudy = "AirConditioner3-Temperature",
                            ResultCaseChange = "5-15",
                            ResultCaseType = "Decrease",
                            ResultType = "ItemMetaData"
                        },
                        new
                        {
                            Id = new Guid("909d51bb-b5b6-49cc-9470-eb4752fd6ede"),
                            ActionAggregateId = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            CaseStudy = "Degree",
                            ResultCaseChange = "7",
                            ResultCaseType = "Decrease",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("19077f58-7c6a-49f0-9775-e9db8fc04bca"),
                            ActionAggregateId = new Guid("db116b9c-e998-498f-9ca3-f4e8eeeb4b8b"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Stand",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("5364949c-6c41-4a97-8842-d15b8f683959"),
                            ActionAggregateId = new Guid("509c51f0-8991-42e7-bd9f-8c26070d89b6"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Corridor",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("40b6ccb6-dac5-4e37-8b59-cb04fc935be2"),
                            ActionAggregateId = new Guid("b62ca4c5-73ca-462f-a89d-46e42f4fa4b9"),
                            CaseStudy = "KitchenDoor",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("b502a886-40f3-4961-a18d-dbc18112786c"),
                            ActionAggregateId = new Guid("8374b387-564a-46f1-8fe2-0d2da584eb4e"),
                            CaseStudy = "Human2",
                            ResultCaseChange = "Kitchen",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("f408b157-2440-4ba4-9084-56cc94c20d18"),
                            ActionAggregateId = new Guid("23105c78-b2e5-4d0a-8c36-25941b402dac"),
                            CaseStudy = "SafeBox",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("dfd2a195-7b7d-4378-a6b4-bf8b09ef2ee7"),
                            ActionAggregateId = new Guid("890c48e6-5ef6-494e-a2c4-553669331ca3"),
                            CaseStudy = "SafeBox",
                            ResultCaseChange = "Close",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.EnvironmentVariable", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("EnvironmentVariable");

                    b.HasData(
                        new
                        {
                            Type = "Degree",
                            Value = 20
                        },
                        new
                        {
                            Type = "Light",
                            Value = 10
                        },
                        new
                        {
                            Type = "Humidity",
                            Value = 20
                        },
                        new
                        {
                            Type = "Sound",
                            Value = 30
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Human", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeelToDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("MentalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Human");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c21ee14b-6e26-4ae3-a424-b54267987143"),
                            BodyStatus = "Stand",
                            FeelToDegree = "Medium",
                            Location = 2,
                            MentalStatus = "Tired",
                            Name = "Human1"
                        },
                        new
                        {
                            Id = new Guid("b0f8f125-97c8-41a9-a485-63fa4b31ca8c"),
                            BodyStatus = "Stand",
                            FeelToDegree = "Medium",
                            Location = 3,
                            MentalStatus = "Bored",
                            Name = "Human2"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMovable")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b18f392f-e54c-44d8-be26-29fe4def565f"),
                            Description = "House Door",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "HouseDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("4fd24168-e0d2-4a0a-9146-ec8684c76183"),
                            Description = "LivingRoom Door",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "LivingRoomDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("9ae6edf2-e98a-4086-854b-8a650269a968"),
                            Description = "Kitchen Door",
                            IsMovable = false,
                            Location = 1,
                            MetaData = "",
                            Name = "KitchenDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("0697dc50-b75a-44d0-8c63-e0f9f7666e5d"),
                            Description = "Bathroom Door",
                            IsMovable = false,
                            Location = 4,
                            MetaData = "",
                            Name = "BathroomDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("f2d36c8c-7cb4-4ac1-97f1-4bf6e9bc45b6"),
                            Description = "Bedroom1 Door",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "",
                            Name = "Bedroom1Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("3ed8f519-27f8-4eaa-89da-1afe8011dc37"),
                            Description = "Bedroom2 Door",
                            IsMovable = false,
                            Location = 3,
                            MetaData = "",
                            Name = "Bedroom2Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("13a25653-a6bf-4ee1-b33c-8177bb066bc0"),
                            Description = "Balcony Door1",
                            IsMovable = false,
                            Location = 5,
                            MetaData = "",
                            Name = "BalconyDoor1",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("cee7ab00-9d06-4438-ac8c-172f2f6bf3aa"),
                            Description = "Balcony Door2",
                            IsMovable = false,
                            Location = 5,
                            MetaData = "",
                            Name = "BalconyDoor2",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("c630cb1c-c865-46dd-a23e-87f5629d5733"),
                            Description = "Bedroom1 Window",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "",
                            Name = "Bedroom1Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("3570154f-185d-4454-816e-0e5763c4e598"),
                            Description = "Bedroom2 Window",
                            IsMovable = false,
                            Location = 3,
                            MetaData = "",
                            Name = "Bedroom2Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("feb8d427-d1ca-4a01-9a1b-1de8f15f4596"),
                            Description = "Balcony Window",
                            IsMovable = false,
                            Location = 5,
                            MetaData = "",
                            Name = "BalconyWindow",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("56df0284-2600-4399-a0b7-c517cc2711b0"),
                            Description = "Bedroom1 Bed",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "",
                            Name = "Bedroom1Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("15bf35d9-190d-4343-bb81-888dd37fe4a6"),
                            Description = "Bedroom1 AirConditioner",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "",
                            Name = "AirConditioner1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("79d7ce5e-c051-42ae-9a62-273bbaa7b5d4"),
                            Description = "Bedroom1 Computer",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "",
                            Name = "Computer",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("36b103b6-e2be-4744-8507-525418aa208b"),
                            Description = "Bedroom1 Chair",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "",
                            Name = "Chair11",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("2e21e329-b5f5-48d9-a361-c8164e9da993"),
                            Description = "Bedroom1 Lamp",
                            IsMovable = false,
                            Location = 2,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("473e4f87-aead-4adc-bb4a-3eeddfd93788"),
                            Description = "Bedroom2 Bed",
                            IsMovable = false,
                            Location = 3,
                            MetaData = "{\"Temperature\":20,\"Speed\":10}",
                            Name = "Bedroom2Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("ca732900-d773-428e-9752-4b33b154fed9"),
                            Description = "Bedroom2 AirConditioner",
                            IsMovable = false,
                            Location = 3,
                            MetaData = "{\"Temperature\":20,\"Speed\":10}",
                            Name = "AirConditioner2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("b9ce9676-f875-4b4c-b3dc-ed4f14d01646"),
                            Description = "Bedroom2 Laptop",
                            IsMovable = true,
                            Location = 3,
                            MetaData = "{\"Charge\":90,\"IsInCharge\":false}",
                            Name = "Laptop",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("171ba84f-d703-46d1-9edf-ba526ce67ebb"),
                            Description = "Bedroom2 Chair",
                            IsMovable = false,
                            Location = 3,
                            MetaData = "",
                            Name = "Chair21",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("c7e85d25-3424-45fc-bb28-3ee2ad11fcaf"),
                            Description = "Bedroom2 Lamp",
                            IsMovable = false,
                            Location = 3,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("af743ea5-df2b-4ef4-abe2-e9b385d0db1c"),
                            Description = "Kitchen Oven",
                            IsMovable = false,
                            Location = 1,
                            MetaData = "",
                            Name = "Oven",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("ef3c4eb2-d8ac-48cf-a090-76e4a4a52bb0"),
                            Description = "Kitchen Refrigerator",
                            IsMovable = false,
                            Location = 1,
                            MetaData = "",
                            Name = "Refrigerator",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("2f2cbc08-ee50-4128-a4cf-7a89bcf971ef"),
                            Description = "Kitchen WashingMachine",
                            IsMovable = false,
                            Location = 1,
                            MetaData = "",
                            Name = "WashingMachine",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("71d605ae-d911-40ce-a8a8-e8b656c122db"),
                            Description = "Kitchen DishWasher",
                            IsMovable = false,
                            Location = 1,
                            MetaData = "",
                            Name = "DishWasher",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("ef0dc462-dee7-46ba-8a67-f13946f78b90"),
                            Description = "Kitchen Lamp",
                            IsMovable = false,
                            Location = 1,
                            MetaData = "",
                            Name = "Lamp3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("90683171-af93-43e2-8925-7a54edee65cc"),
                            Description = "LivingRoom TV",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "{\"Channel\":1,\"Sound\":60}",
                            Name = "TV",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("3e985ba4-1e87-4741-a204-28a9049bc57b"),
                            Description = "LivingRoom Sofa1",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "{\"Capacity\":1}",
                            Name = "Sofa1",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("9830c37b-a75e-43d6-b7d5-c24f32ff479e"),
                            Description = "LivingRoom Sofa2",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "{\"Capacity\":2}",
                            Name = "Sofa2",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("d560a918-703e-40e2-83b5-c412526a301e"),
                            Description = "LivingRoom Sofa3",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "{\"Capacity\":3}",
                            Name = "Sofa3",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("6dd43a57-bb60-4842-8dea-6a518817b2e3"),
                            Description = "LivingRoom Table",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "Table",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("ec977a0a-86cb-4746-953c-0fc191bc3c15"),
                            Description = "LivingRoom Chair1",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "Chair1",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("5befc2e4-9a34-4081-aa74-04b4489c9d00"),
                            Description = "LivingRoom Chair2",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "Chair2",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("70e8f659-0a29-4c36-8f71-dd5c97d1b0b8"),
                            Description = "LivingRoom Chair3",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "Chair3",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("56f31d65-1489-4083-b902-3991d2b002f3"),
                            Description = "LivingRoom Chair4",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "Chair4",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("9fd8a48a-cf06-45d5-b5f8-26ad9d6d3c94"),
                            Description = "LivingRoom AirConditioner",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "{\"Temperature\":20,\"Speed\":10}",
                            Name = "AirConditioner3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("13ec032b-28a6-4fb7-965e-76d676117714"),
                            Description = "LivingRoom Lamp",
                            IsMovable = false,
                            Location = 0,
                            MetaData = "",
                            Name = "Lamp4",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("7519c829-18ef-476e-a985-edbbf264499d"),
                            Description = "Bathroom Lamp",
                            IsMovable = false,
                            Location = 4,
                            MetaData = "",
                            Name = "Lamp5",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("bc024886-b45f-406c-a24e-7332d0c12bbf"),
                            Description = "Balcony Lamp",
                            IsMovable = false,
                            Location = 5,
                            MetaData = "",
                            Name = "Lamp6",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("1e83cfb2-7d44-4b8d-9c70-f611c4c6924d"),
                            Description = "Corridor Lamp",
                            IsMovable = false,
                            Location = 6,
                            MetaData = "",
                            Name = "Lamp7",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("e608c193-6792-4fbd-80f6-788337916592"),
                            Description = "Safe Box",
                            IsMovable = false,
                            Location = 6,
                            MetaData = "",
                            Name = "SafeBox",
                            State = "Close",
                            Type = "Openable"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.NextAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<int>("Possibility")
                        .HasColumnType("int");

                    b.HasKey("Id", "ActionAggregateId");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("NextAction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            ActionAggregateId = new Guid("a1d6d20f-b4de-4d59-a3eb-a8b16811f2a4"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            ActionAggregateId = new Guid("e06f8346-a23c-4523-842f-729f25ddbb44"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("75ea5975-decd-4a20-863b-52fc9e582d43"),
                            ActionAggregateId = new Guid("e75a58c7-d48b-4c43-8d2d-d439c8e86578"),
                            Delay = 100,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            ActionAggregateId = new Guid("09c8455e-3eef-4036-994b-bf7ce39bf235"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            ActionAggregateId = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            Delay = 200,
                            Possibility = 50
                        },
                        new
                        {
                            Id = new Guid("23105c78-b2e5-4d0a-8c36-25941b402dac"),
                            ActionAggregateId = new Guid("016d426a-2566-42a6-8796-2244e6f377ec"),
                            Delay = 150,
                            Possibility = 50
                        },
                        new
                        {
                            Id = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            ActionAggregateId = new Guid("90f6ccf8-707d-4873-a4bf-f41b27610820"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            ActionAggregateId = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            Delay = 200,
                            Possibility = 30
                        },
                        new
                        {
                            Id = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            ActionAggregateId = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("3ff70002-1fd6-401b-8f7e-dad3253cc7fc"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("54e3ecd1-47a4-41db-a036-2402c74ae7ed"),
                            ActionAggregateId = new Guid("f1992220-dfad-4d92-867f-fec102e47f0a"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            ActionAggregateId = new Guid("31d83d8e-871e-4f2b-aa34-073258580722"),
                            Delay = 350,
                            Possibility = 70
                        },
                        new
                        {
                            Id = new Guid("0d777c34-dd39-4252-9f64-8d67a448fd64"),
                            ActionAggregateId = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            Delay = 200,
                            Possibility = 10
                        },
                        new
                        {
                            Id = new Guid("dd1f9853-c241-4258-8059-cdf5e1432d34"),
                            ActionAggregateId = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            Delay = 200,
                            Possibility = 90
                        },
                        new
                        {
                            Id = new Guid("afc68b69-be7b-4ac2-9f4a-e27c251897e9"),
                            ActionAggregateId = new Guid("db116b9c-e998-498f-9ca3-f4e8eeeb4b8b"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("b62ca4c5-73ca-462f-a89d-46e42f4fa4b9"),
                            ActionAggregateId = new Guid("509c51f0-8991-42e7-bd9f-8c26070d89b6"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("8374b387-564a-46f1-8fe2-0d2da584eb4e"),
                            ActionAggregateId = new Guid("b62ca4c5-73ca-462f-a89d-46e42f4fa4b9"),
                            Delay = 300,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("890c48e6-5ef6-494e-a2c4-553669331ca3"),
                            ActionAggregateId = new Guid("23105c78-b2e5-4d0a-8c36-25941b402dac"),
                            Delay = 1800,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("509c51f0-8991-42e7-bd9f-8c26070d89b6"),
                            ActionAggregateId = new Guid("890c48e6-5ef6-494e-a2c4-553669331ca3"),
                            Delay = 600,
                            Possibility = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionCondition", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("Conditions")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionResult", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("Results")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.NextAction", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("NextActions")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionAggregate", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("NextActions");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
