// <auto-generated />
using System;
using FakeEventGenerator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeEventGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(FakeEventGeneratorDBContext))]
    partial class FakeEventGeneratorDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartPossibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActionAggregate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("330c8533-8390-48c4-8065-36d0322bba86"),
                            Delay = 500,
                            Description = "Open Door1 Of Balcony",
                            Name = "Open-BalconyDoor1",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            Delay = 500,
                            Description = "Move To Balcony Human1 Via Bedroom1",
                            Name = "Move-Balcony-Bedroom1",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            Delay = 100,
                            Description = "Open Window Of Balcony",
                            Name = "Open-BalconyWindow",
                            StartPossibility = 100
                        },
                        new
                        {
                            Id = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            Delay = 50,
                            Description = "Sit Under BalconyWindow",
                            Name = "Sit-BalconyWindow",
                            StartPossibility = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCaseExpectation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("ActionCondition");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46d52c1a-5977-43ee-891d-52613868335a"),
                            ActionAggregateId = new Guid("330c8533-8390-48c4-8065-36d0322bba86"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Bedroom1",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("ded7721a-c61c-4481-b841-a0ef35db4a03"),
                            ActionAggregateId = new Guid("330c8533-8390-48c4-8065-36d0322bba86"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("5fdbfae9-aa23-43c9-bf13-6dbbd921df06"),
                            ActionAggregateId = new Guid("330c8533-8390-48c4-8065-36d0322bba86"),
                            CaseStudy = "BalconyDoor1",
                            ConditionCaseExpectation = "Close",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("07c40895-7579-4948-b46a-2dfd98fe5c0b"),
                            ActionAggregateId = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Bedroom1",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("0ae606cd-6ee2-4c69-b8ba-e18a7ad23e72"),
                            ActionAggregateId = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("3c296e51-3209-4f0c-b76e-d2358a1d1fd4"),
                            ActionAggregateId = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            CaseStudy = "BalconyDoor1",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("8528c930-e8b5-4f7f-a70f-6bfa8c295201"),
                            ActionAggregateId = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Balcony",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("8dd870f8-799c-47a0-aaac-037e92d7cdfa"),
                            ActionAggregateId = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Stand",
                            ConditionCaseType = "StateIs",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("d798ab23-7fbb-4d7f-8f16-ca28abf5b020"),
                            ActionAggregateId = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Balcony",
                            ConditionCaseType = "IsIn",
                            ConditionType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("2f25a3f3-4bf5-49dd-afe7-33730d456641"),
                            ActionAggregateId = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Sit",
                            ConditionCaseType = "StateIsNot",
                            ConditionType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("c7c455a3-4b50-40a2-b87f-bf1c8203c129"),
                            ActionAggregateId = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            CaseStudy = "Human1",
                            ConditionCaseExpectation = "Tired",
                            ConditionCaseType = "StateIs",
                            ConditionType = "MentalStatus"
                        },
                        new
                        {
                            Id = new Guid("33fa3e5b-1fc3-45fc-a21b-b97fdbbf878b"),
                            ActionAggregateId = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            CaseStudy = "BalconyWindow",
                            ConditionCaseExpectation = "Open",
                            ConditionCaseType = "StateIs",
                            ConditionType = "ItemState"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCaseChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("ActionResult");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f804eb21-3a1d-46eb-96c6-d769a1d86508"),
                            ActionAggregateId = new Guid("330c8533-8390-48c4-8065-36d0322bba86"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "25-79",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("0c9a02f5-7998-44e0-9e96-93ead303633b"),
                            ActionAggregateId = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "25-81",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("60510682-565c-4a79-952a-609c4827567b"),
                            ActionAggregateId = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "50-99",
                            ResultCaseType = "Position",
                            ResultType = "HumanPosition"
                        },
                        new
                        {
                            Id = new Guid("1813d626-b256-4de1-8d99-e2d3fae7d5be"),
                            ActionAggregateId = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            CaseStudy = "BalconyWindow",
                            ResultCaseChange = "Open",
                            ResultCaseType = "State",
                            ResultType = "ItemState"
                        },
                        new
                        {
                            Id = new Guid("6a316ec5-a09f-4628-a4e9-bdcb93d200b7"),
                            ActionAggregateId = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            CaseStudy = "Light",
                            ResultCaseChange = "20-IF:Day",
                            ResultCaseType = "Increase",
                            ResultType = "Environment"
                        },
                        new
                        {
                            Id = new Guid("4283e834-68e0-432a-89e6-a71ac030e38b"),
                            ActionAggregateId = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Sit",
                            ResultCaseType = "State",
                            ResultType = "HumanBodyStatus"
                        },
                        new
                        {
                            Id = new Guid("03fff1c9-cd4a-4337-810c-8510a6218dc7"),
                            ActionAggregateId = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            CaseStudy = "Human1",
                            ResultCaseChange = "Normal",
                            ResultCaseType = "State",
                            ResultType = "MentalStatus"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.EnvironmentVariable", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("EnvironmentVariable");

                    b.HasData(
                        new
                        {
                            Type = "Degree",
                            Value = 20
                        },
                        new
                        {
                            Type = "Light",
                            Value = 10
                        },
                        new
                        {
                            Type = "Humidity",
                            Value = 20
                        },
                        new
                        {
                            Type = "Sound",
                            Value = 30
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Human", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("FeelToDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Human");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14bb7a62-23ff-4a78-bb94-46c1ee3ea5e9"),
                            BodyStatus = "Stand",
                            CoordinateX = 10,
                            CoordinateY = 74,
                            FeelToDegree = "Medium",
                            MentalStatus = "Tired",
                            Name = "Human1"
                        },
                        new
                        {
                            Id = new Guid("0f7f7af7-f0e3-43ce-a27f-762a2ace33ee"),
                            BodyStatus = "Stand",
                            CoordinateX = 75,
                            CoordinateY = 65,
                            FeelToDegree = "Medium",
                            MentalStatus = "Normal",
                            Name = "Human2"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMovable")
                        .HasColumnType("bit");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c91a2fb2-2c69-4ce3-a512-89cebd7106eb"),
                            CoordinateX = 55,
                            CoordinateY = 0,
                            Description = "House Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "HouseDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("351357ee-47a8-4426-a79d-dc13d248af30"),
                            CoordinateX = 55,
                            CoordinateY = 30,
                            Description = "LivingRoom Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "LivingRoomDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("5194bfba-5ec7-44f3-bfce-dc69ba932d49"),
                            CoordinateX = 15,
                            CoordinateY = 30,
                            Description = "Kitchen Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "KitchenDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("ec87577d-82ac-466c-8be8-5f8469db4dca"),
                            CoordinateX = 90,
                            CoordinateY = 30,
                            Description = "Bathroom Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BathroomDoor",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("cadd09d8-79ec-4c7b-a324-695b3f2dc5c0"),
                            CoordinateX = 25,
                            CoordinateY = 50,
                            Description = "Bedroom1 Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom1Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("222b948c-cd40-49e1-b488-fca33f30ceb1"),
                            CoordinateX = 75,
                            CoordinateY = 50,
                            Description = "Bedroom2 Door",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom2Door",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("b516ff6a-bae6-453b-9e44-347e45423b4c"),
                            CoordinateX = 25,
                            CoordinateY = 80,
                            Description = "Balcony Door1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BalconyDoor1",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("eab071be-e981-4b59-ad88-db19f5fb5488"),
                            CoordinateX = 75,
                            CoordinateY = 80,
                            Description = "Balcony Door2",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BalconyDoor2",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("892f9226-af81-427c-800a-0a47f934cd96"),
                            CoordinateX = 0,
                            CoordinateY = 65,
                            Description = "Bedroom1 Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom1Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("d5d22ce2-ed44-485a-9081-bc77897e953d"),
                            CoordinateX = 100,
                            CoordinateY = 65,
                            Description = "Bedroom2 Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom2Window",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("bd6be63c-d59f-4ced-b37f-f7e6d8b76949"),
                            CoordinateX = 50,
                            CoordinateY = 100,
                            Description = "Balcony Window",
                            IsMovable = false,
                            MetaData = "",
                            Name = "BalconyWindow",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("61fcc839-7b1c-41b9-ac3e-5597567cb45b"),
                            CoordinateX = 40,
                            CoordinateY = 65,
                            Description = "Bedroom1 Bed",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Bedroom1Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("a2d5210e-cfe1-4453-89d4-cb748ed85c68"),
                            CoordinateX = 49,
                            CoordinateY = 55,
                            Description = "Bedroom1 AirConditioner",
                            IsMovable = false,
                            MetaData = "",
                            Name = "AirConditioner1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("db0f80a5-209a-404a-b4cf-2e1a91f5b647"),
                            CoordinateX = 10,
                            CoordinateY = 79,
                            Description = "Bedroom1 Computer",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Computer",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("cc0146c8-c5ba-45ff-95c9-6ddb8449fbcd"),
                            CoordinateX = 10,
                            CoordinateY = 75,
                            Description = "Bedroom1 Chair",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair11",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("337a87f7-285a-4264-af1e-dce2ae6edc05"),
                            CoordinateX = 25,
                            CoordinateY = 65,
                            Description = "Bedroom1 Lamp",
                            IsMovable = false,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp1",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("5545f5e3-86a4-4622-aded-e876f116b71f"),
                            CoordinateX = 60,
                            CoordinateY = 65,
                            Description = "Bedroom2 Bed",
                            IsMovable = false,
                            MetaData = "{\"Tempreture\":20,\"Speed\":10}",
                            Name = "Bedroom2Bed",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("03833720-c84f-48f3-845f-cecaa95423ef"),
                            CoordinateX = 51,
                            CoordinateY = 55,
                            Description = "Bedroom2 AirConditioner",
                            IsMovable = false,
                            MetaData = "{\"Tempreture\":20,\"Speed\":10}",
                            Name = "AirConditioner2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("ccb64e2b-0115-4f9b-b2b3-94e88db5d161"),
                            CoordinateX = 90,
                            CoordinateY = 79,
                            Description = "Bedroom2 Laptop",
                            IsMovable = true,
                            MetaData = "{\"Charge\":90,\"IsInCharge\":false}",
                            Name = "Laptop",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("4d22cd79-3f6c-4cf5-abd4-764b01403c09"),
                            CoordinateX = 90,
                            CoordinateY = 75,
                            Description = "Bedroom2 Chair",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair21",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("91fcd1cb-869e-40de-a531-91765f0fd6f3"),
                            CoordinateX = 75,
                            CoordinateY = 65,
                            Description = "Bedroom2 Lamp",
                            IsMovable = false,
                            MetaData = "{\"Severity\":20}",
                            Name = "Lamp2",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("a4b0edd0-c007-4d16-a67e-64882197971a"),
                            CoordinateX = 15,
                            CoordinateY = 1,
                            Description = "Kitchen Oven",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Oven",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("a69fd101-15b1-4561-a618-fcdb3cd4c2e6"),
                            CoordinateX = 1,
                            CoordinateY = 15,
                            Description = "Kitchen Refrigerator",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Refrigerator",
                            State = "Close",
                            Type = "Openable"
                        },
                        new
                        {
                            Id = new Guid("60ee9f38-825a-446f-a4f4-721c7d75c10e"),
                            CoordinateX = 29,
                            CoordinateY = 15,
                            Description = "Kitchen WashingMachine",
                            IsMovable = false,
                            MetaData = "",
                            Name = "WashingMachine",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("8aaad363-add4-47e3-8b6a-9166a623df5e"),
                            CoordinateX = 25,
                            CoordinateY = 1,
                            Description = "Kitchen DishWasher",
                            IsMovable = false,
                            MetaData = "",
                            Name = "DishWasher",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("fec6eaf3-807a-45e5-b7a7-1f8ae0898e3c"),
                            CoordinateX = 15,
                            CoordinateY = 15,
                            Description = "Kitchen Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("f985353a-d9a6-4e54-af72-42cce33e4c93"),
                            CoordinateX = 79,
                            CoordinateY = 15,
                            Description = "LivingRoom TV",
                            IsMovable = false,
                            MetaData = "{\"Channel\":1,\"Sound\":20}",
                            Name = "TV",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("bd8555e2-3bfb-485e-9584-7d553f1fdd64"),
                            CoordinateX = 70,
                            CoordinateY = 20,
                            Description = "LivingRoom Sofa1",
                            IsMovable = false,
                            MetaData = "{\"Capacity\":1}",
                            Name = "Sofa1",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("eca535f8-09bc-4e26-84f6-c3c06099e235"),
                            CoordinateX = 70,
                            CoordinateY = 10,
                            Description = "LivingRoom Sofa2",
                            IsMovable = false,
                            MetaData = "{\"Capacity\":2}",
                            Name = "Sofa2",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("e0f48fe6-c700-4aa1-8d84-800c75fa715a"),
                            CoordinateX = 60,
                            CoordinateY = 15,
                            Description = "LivingRoom Sofa3",
                            IsMovable = false,
                            MetaData = "{\"Capacity\":3}",
                            Name = "Sofa3",
                            State = "NotFull",
                            Type = "UseWithCapacity"
                        },
                        new
                        {
                            Id = new Guid("813eaa5b-a46a-4fd7-af17-df9f1f2f2996"),
                            CoordinateX = 40,
                            CoordinateY = 15,
                            Description = "LivingRoom Table",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Table",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("18793e8f-eaeb-4af7-8a74-7b551fe0b350"),
                            CoordinateX = 35,
                            CoordinateY = 15,
                            Description = "LivingRoom Chair1",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair1",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("b2184ad9-0644-4d8a-bf6d-8a245e650c8e"),
                            CoordinateX = 45,
                            CoordinateY = 15,
                            Description = "LivingRoom Chair2",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair2",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("f59f3682-5f46-4940-9153-b2664700d56b"),
                            CoordinateX = 40,
                            CoordinateY = 10,
                            Description = "LivingRoom Chair3",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair3",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("bd6b3d7b-5842-48fd-8746-f75b82d468a1"),
                            CoordinateX = 40,
                            CoordinateY = 20,
                            Description = "LivingRoom Chair4",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Chair4",
                            State = "NotBeUsing",
                            Type = "Usable"
                        },
                        new
                        {
                            Id = new Guid("9e0c6f82-f310-4134-9a8f-c171fcc4b61c"),
                            CoordinateX = 40,
                            CoordinateY = 29,
                            Description = "LivingRoom AirConditioner",
                            IsMovable = false,
                            MetaData = "{\"Tempreture\":20,\"Speed\":10}",
                            Name = "AirConditioner3",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("1a62f8b2-5698-4d67-befe-d45192160f0e"),
                            CoordinateX = 55,
                            CoordinateY = 15,
                            Description = "LivingRoom Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp4",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("d9e462fe-0561-4823-ab2b-ada3ccf797fb"),
                            CoordinateX = 90,
                            CoordinateY = 15,
                            Description = "Bathroom Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp5",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("e91fdf09-2ef3-4c0b-8025-452b4846a4eb"),
                            CoordinateX = 50,
                            CoordinateY = 90,
                            Description = "Balcony Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp6",
                            State = "Off",
                            Type = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("98b4113a-cc22-4b29-b7b8-c117d7fce9c0"),
                            CoordinateX = 50,
                            CoordinateY = 40,
                            Description = "Corridor Lamp",
                            IsMovable = false,
                            MetaData = "",
                            Name = "Lamp7",
                            State = "Off",
                            Type = "Electronic"
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.NextAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<int>("Possibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionAggregateId");

                    b.ToTable("NextAction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            ActionAggregateId = new Guid("330c8533-8390-48c4-8065-36d0322bba86"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            ActionAggregateId = new Guid("444a4901-066b-4bee-9786-2a80e565c539"),
                            Delay = 200,
                            Possibility = 100
                        },
                        new
                        {
                            Id = new Guid("d98c2485-7ad0-4d9d-92c8-594fba0ad286"),
                            ActionAggregateId = new Guid("4d49e450-ccd5-4dfc-9aec-d2c4b05a048c"),
                            Delay = 100,
                            Possibility = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.PartOfHouse", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coordinate1X")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate1Y")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate2X")
                        .HasColumnType("int");

                    b.Property<int>("Coordinate2Y")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("PartOfHouse");

                    b.HasData(
                        new
                        {
                            Type = "House",
                            Coordinate1X = 0,
                            Coordinate1Y = 0,
                            Coordinate2X = 100,
                            Coordinate2Y = 100
                        },
                        new
                        {
                            Type = "LivingRoom",
                            Coordinate1X = 0,
                            Coordinate1Y = 0,
                            Coordinate2X = 30,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Kitchen",
                            Coordinate1X = 30,
                            Coordinate1Y = 0,
                            Coordinate2X = 80,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Bathroom",
                            Coordinate1X = 80,
                            Coordinate1Y = 0,
                            Coordinate2X = 100,
                            Coordinate2Y = 30
                        },
                        new
                        {
                            Type = "Corridor",
                            Coordinate1X = 0,
                            Coordinate1Y = 30,
                            Coordinate2X = 100,
                            Coordinate2Y = 50
                        },
                        new
                        {
                            Type = "Bedroom1",
                            Coordinate1X = 0,
                            Coordinate1Y = 50,
                            Coordinate2X = 50,
                            Coordinate2Y = 80
                        },
                        new
                        {
                            Type = "Bedroom2",
                            Coordinate1X = 50,
                            Coordinate1Y = 50,
                            Coordinate2X = 100,
                            Coordinate2Y = 80
                        },
                        new
                        {
                            Type = "Balcony",
                            Coordinate1X = 0,
                            Coordinate1Y = 80,
                            Coordinate2X = 100,
                            Coordinate2Y = 100
                        });
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionCondition", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("Conditions")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionResult", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("Results")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.NextAction", b =>
                {
                    b.HasOne("FakeEventGenerator.Domain.Models.ActionAggregate", "ActionAggregate")
                        .WithMany("NextActions")
                        .HasForeignKey("ActionAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionAggregate");
                });

            modelBuilder.Entity("FakeEventGenerator.Domain.Models.ActionAggregate", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("NextActions");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
